from contextlib import AbstractContextManager
from typing import Any, Protocol


class Repository(Protocol):
    def content_units(self, version_id: str, *, offset=0, limit=50, search="") -> dict: ...
    def get(self, table: str, key: Any, *, lock=False) -> dict | None: ...
    def find(
        self,
        table: str,
        filters: dict | None = None,
        *,
        order=(),
        limit=None,
        lock=False,
        skip_locked=False,
    ) -> list[dict]: ...
    def insert(self, table: str, values: dict) -> dict: ...
    def update(self, table: str, key: Any, values: dict) -> None: ...
    def delete(self, table: str, filters: dict) -> None: ...
    def count(self, table: str, filters: dict) -> int: ...
    def ensure_checkpoint(self, stream: str) -> None: ...
    def sync_upsert(self, table: str, values: dict) -> str: ...
    def stale_tasks(self, cutoff) -> list[dict]: ...
    def health(self) -> None: ...
    def list_resources(
            self,
            *,
            keyword: str | None,
            subject_id: str | None,
            grade_level_id: str | None,
            resource_type_code: str | None,
            offset: int,
            limit: int,
    ) -> tuple[list[dict], int]: ...


class UnitOfWork(Protocol):
    def __call__(self) -> AbstractContextManager[Repository]: ...


